// <auto-generated />
using System;
using ApiCatalogo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EscalaSegurancaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240729132157_v01")]
    partial class v01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EscalaSegurancaAPI.Models.Escala", b =>
                {
                    b.Property<int>("EscalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EscalaId"));

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHoraSaida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Inativado")
                        .HasColumnType("boolean");

                    b.HasKey("EscalaId");

                    b.ToTable("Escalas");
                });

            modelBuilder.Entity("EscalaSegurancaAPI.Models.Local", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocalId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Inativado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LocalId");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("EscalaSegurancaAPI.Models.Policial", b =>
                {
                    b.Property<int>("PolicialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PolicialId"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<bool?>("Inativado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PolicialId");

                    b.ToTable("Policiais");
                });

            modelBuilder.Entity("MarcacaoEscala", b =>
                {
                    b.Property<int>("MarcacaoEscalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarcacaoEscalaId"));

                    b.Property<int>("EscalaId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Inativado")
                        .HasColumnType("boolean");

                    b.Property<int>("LocalId")
                        .HasColumnType("integer");

                    b.Property<int>("PolicialId")
                        .HasColumnType("integer");

                    b.HasKey("MarcacaoEscalaId");

                    b.HasIndex("EscalaId");

                    b.HasIndex("LocalId");

                    b.HasIndex("PolicialId");

                    b.ToTable("Marcacoes");
                });

            modelBuilder.Entity("MarcacaoEscala", b =>
                {
                    b.HasOne("EscalaSegurancaAPI.Models.Escala", "Escala")
                        .WithMany("MarcacoesEscala")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaSegurancaAPI.Models.Local", "Local")
                        .WithMany("MarcacoesEscala")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaSegurancaAPI.Models.Policial", "Policial")
                        .WithMany("MarcacoesEscala")
                        .HasForeignKey("PolicialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");

                    b.Navigation("Local");

                    b.Navigation("Policial");
                });

            modelBuilder.Entity("EscalaSegurancaAPI.Models.Escala", b =>
                {
                    b.Navigation("MarcacoesEscala");
                });

            modelBuilder.Entity("EscalaSegurancaAPI.Models.Local", b =>
                {
                    b.Navigation("MarcacoesEscala");
                });

            modelBuilder.Entity("EscalaSegurancaAPI.Models.Policial", b =>
                {
                    b.Navigation("MarcacoesEscala");
                });
#pragma warning restore 612, 618
        }
    }
}
